permalink: /:year/:month/:day/:title.html
paginate: 10
markdown: kramdown

kramdown:
  input: GFM

# 作者信息
author: 
  name: 张明云
  email: zmywly8866@gmail.com
  link: http://blog.csdn.net/ekeuy
  weibo: http://weibo.com/UperOne
  github: https://github.com/zmywly8866

# 站点信息
title: 张明云的博客 
description: 张明云的博客
url: http://zmywly8866.github.io
rss_url: /pages/atom.xml

# gavatar头像及Favicon
gavatar: http://img.my.csdn.net/uploads/201411/20/1416487512_8950.png
favicon: http://yansu-uploads.stor.sinaapp.com/imgs/favicon.ico

# google analytics 设置
ga:
  id: UA-56952211-1
  url: zmywly8866.github.io

# disqus 设置
disqus:
  shortname: zmywly8866

# 主题设置，自动激活某个标签
active: 技术

# 首页除了最新文章外显示分类
cates: 
  - Android

# 中文本地化
locals:
  tags: 标签
  about: 关于
  newest: 最新文章
  archive: 归档
  content: 目录
