permalink: /:year/:month/:day/:title.html
paginate: 50
markdown: kramdown

kramdown:
  input: GFM

# 作者信息
author: 
  name: 8bit
  email: cdb1t1000@gmail.com
  github: https://github.com/1000b/

# 站点信息
title: 8bit 
description: 
url: http://1000b.github.io
rss_url: /pages/atom.xml

# gavatar头像及Favicon
gavatar: http://img.my.csdn.net/uploads/201411/21/1416528891_3612.png
favicon: http://img.my.csdn.net/uploads/201411/21/1416528891_9081.png

# google analytics 设置
ga:
  id: UA-56952211-1
  url: 10000.github.io

# disqus 设置
disqus:
  shortname: zmywly8866

# 主题设置，自动激活某个标签
active: 技术

# 中文本地化
locals:
  tags: 标签
  about: 关于
  newest: 最新文章
  archive: 归档
  content: 目录
